name: Build Apk z5
on:
  workflow_dispatch:
    inputs:
      retentionDays:
        description: "The number of days to retain the uploaded APK artifact on GitHub."
        required: true
        default: "10"
      repo-dir:
        description: 'directory containing settings.gradle ("/..")'
      module:
        description: 'module'
        required: true
        default: 'app'
      repository :
        description: 'git clone url'
        required: true
   
   
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

     - name: clone
       run: |
         git clone ${{ github.event.inputs.repository }}
         echo "projectName=$(basename -s .git ${{ github.event.inputs.repo-url }})" >> $GITHUB_ENV

       
     - name: Setup JDK
       uses: actions/setup-java@v4
       with:
          distribution: "temurin"
          java-version: 17

          
     - name: build
       run: |
          cd ${{ env.projectName }}${{ github.event.inputs.repo-dir }}
          chmod +x gradlew
          ./gradlew ${{ github.event.inputs.module }} --stacktrace

 
     - name: Upload the APK artifact 
       uses: actions/upload-artifact@v4
       with:
         name: apk-archive
         path: ./**/*.apk
         retention-days: ${{ github.event.inputs.retentionDays }}

 

        
 
