name: JDK Build Apk 2024
on:
  workflow_dispatch:
    inputs:
      retentionDays:
        description: "The number of days to retain the uploaded APK artifact on GitHub."
        required: true
        default: "10"
      repo-dir:
        description: 'directory containing settings.gradle ("/..")'
      repository :
        description: 'git clone url'
        required: true
      repo-commit:
        description: 'commit'
    
   
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

     - name: clone
       run: |
         git clone ${{ github.event.inputs.repository }}
         echo "projectName=$(basename -s .git ${{ github.event.inputs.repository }})" >> $GITHUB_ENV

     - name: select commit
       if: ${{ github.event.inputs.repo-commit != '' }}
       run: |
         cd ${{ env.projectName }}
         git checkout ${{ github.event.inputs.repo-commit }}
          
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         distribution: "zulu"
         java-version: 11
         cache: "gradle"
          
     - name: build
       run: |
          cd ${{ env.projectName }}${{ github.event.inputs.repo-dir }}
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

 
     - name: Upload the APK artifact 
       uses: actions/upload-artifact@v4
       with:
         name: apk-archive
         path: ./**/*.apk
         retention-days: ${{ github.event.inputs.retentionDays }}

 

        
 
