name: Build Android APK
workflow_dispatch:
  
inputs:
      repo-url:
        description: 'git clone url'
        required: true
      repo-commit:
        description: 'commit'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ninja 
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17' 
          
    - name: clone
      run: |
          git clone ${{ github.event.inputs.repo-url }}
          echo "projectName=$(basename -s .git ${{ github.event.inputs.repo-url }})" >> $GITHUB_ENV
          echo "dirName=$(echo ${{ github.event.inputs.repo-dir }} | sed -r 's/[/]+/ - /g')" >> $GITHUB_ENV
        
    - name: select commit
      if: ${{ github.event.inputs.repo-commit != '' }}
      run: |
          cd ${{ env.projectName }}
          git checkout ${{ github.event.inputs.repo-commit }}

    - name: build
      run: |
          cd ${{ env.projectName }}${{ github.event.inputs.repo-dir }}
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew ${{ github.event.inputs.module }}:assembleRelease

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.projectName }}${{ env.dirName }} - ${{ github.event.inputs.module }}
          path: ${{ github.workspace }}/${{ env.projectName }}${{ github.event.inputs.repo-dir }}/${{ github.event.inputs.module }}/build/outputs/apk/release/*.apk 



             
